toolchain: remove stdalign.h
LLVM's stdalign.h does not define alignof() in case __STDC_VERSION__ is
not defined. Remove stdalign.h until this problem is defined in upstream
LLVM and let ports include stdalign.h in base instead.

devel/nspr without this change fails to compile with the error:
priometh.c:290:72: error: unexpected type name 'PRNetAddr': expected expression
  290 |         *raddr = (PRNetAddr*) __builtin_align_up(buf + amount, alignof(PRNetAddr));
      |                                                                        ^